Patch to disable containerizedengine/update_test.go
This file fails to build, this is mentioned at:
<https://github.com/docker/cli/pull/1561>

Build failure:

    # github.com/docker/cli/internal/containerizedengine [github.com/docker/cli/internal/containerizedengine.test]
    internal/containerizedengine/update_test.go:80:4: cannot use image (type *fakeImage) as type containerd.Image in return argument:
        *fakeImage does not implement containerd.Image (missing Labels method)
    internal/containerizedengine/update_test.go:95:5: cannot use image (type *fakeImage) as type containerd.Image in return argument:
        *fakeImage does not implement containerd.Image (missing Labels method)
    internal/containerizedengine/update_test.go:127:4: cannot use image (type *fakeImage) as type containerd.Image in return argument:
        *fakeImage does not implement containerd.Image (missing Labels method)
    internal/containerizedengine/update_test.go:252:4: cannot use image (type *fakeImage) as type containerd.Image in return argument:
        *fakeImage does not implement containerd.Image (missing Labels method)

Signed-off-by: Arnaud Rebillout <arnaud.rebillout@collabora.com>