Vendor coreos/go-systemd, docker requires v17
Build logs:

  # github.com/docker/docker/daemon/listeners
  daemon/listeners/listeners_linux.go:65:43: not enough arguments in call to activation.TLSListeners
          have (*tls.Config)
          want (bool, *tls.Config)
  daemon/listeners/listeners_linux.go:67:40: not enough arguments in call to activation.Listeners
          have ()
          want (bool)

Signed-off-by: Arnaud Rebillout <arnaud.rebillout@collabora.com>